const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const userSchema = new mongoose.Schema(
  {
    name:         { type: String, required: true, trim: true },
    email:        { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: { type: String, default: null },   // null for OAuth-only accounts
    phone:        { type: String, trim: true },

    role: {
      type: String,
      enum: ['admin', 'superAdmin', 'agencyAdmin', 'fleetManager', 'driver', 'passenger'],
      required: true,
    },

    // agencyId is required for agencyAdmin, fleetManager and driver roles; null for platform admin/passenger
    agencyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Agency',
      default: null,
    },

    status: { type: String, enum: ['active', 'inactive'], default: 'active' },

    loginAttempts: { type: Number, default: 0 },
    lockUntil:     { type: Date },
    lastLogin:     { type: Date },

    refreshTokenHash: { type: String },

    // Password reset (FR-A05)
    passwordResetToken:   { type: String },
    passwordResetExpires: { type: Date },

    // Staff ID for drivers and fleet managers — generated by the system on account creation
    // Format: {AGENCY_SHORTCODE}-{DRV|FLM}-{3-digit-seq}  e.g. GLD-DRV-001
    staffId: { type: String, uppercase: true, trim: true },

    // OAuth providers (passenger sign-in with Google / Apple)
    googleId: { type: String, default: null },
    appleId:  { type: String, default: null },

    // Passenger-specific
    bookingCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

// Indexes
// email uniqueness already enforced by `unique: true` on the field above
userSchema.index({ staffId: 1 }, { unique: true, sparse: true });
userSchema.index({ agencyId: 1, role: 1 });
userSchema.index({ role: 1, status: 1 });

// Password comparison — returns false for OAuth-only accounts (no passwordHash)
userSchema.methods.comparePassword = async function (plain) {
  if (!this.passwordHash) return false;
  return bcrypt.compare(plain, this.passwordHash);
};

// Account lock check
userSchema.virtual('isLocked').get(function () {
  return this.lockUntil && this.lockUntil > Date.now();
});

// Sanitise output — never expose passwordHash or tokens
userSchema.methods.toSafeObject = function () {
  const obj = this.toObject();
  delete obj.passwordHash;
  delete obj.refreshTokenHash;
  delete obj.loginAttempts;
  delete obj.lockUntil;
  return obj;
};

module.exports = mongoose.model('User', userSchema);
