global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'movesmart-api'
    static_configs:
      - targets: ['movesmart-api:5000']
    metrics_path: '/metrics'

  - job_name: 'movesmart-ml'
    static_configs:
      - targets: ['movesmart-ml:8000']
    metrics_path: '/metrics'
